// <auto-generated />
using Designa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Designa.Migrations
{
    [DbContext(typeof(DesignaContext))]
    [Migration("20240331231057_AddTbVinculoIrmaoComParte")]
    partial class AddTbVinculoIrmaoComParte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("Designa.Models.Irmao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Irmaos");
                });

            modelBuilder.Entity("Designa.Models.IrmaoParte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IrmaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IrmaoId");

                    b.HasIndex("ParteId");

                    b.ToTable("IrmaoParte");
                });

            modelBuilder.Entity("Designa.Models.Parte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Minutos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReuniaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReuniaoId");

                    b.ToTable("Partes");
                });

            modelBuilder.Entity("Designa.Models.Reuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Semana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reunioes");
                });

            modelBuilder.Entity("Designa.Models.IrmaoParte", b =>
                {
                    b.HasOne("Designa.Models.Irmao", "Irmao")
                        .WithMany("IrmaoPartes")
                        .HasForeignKey("IrmaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Designa.Models.Parte", "Parte")
                        .WithMany("PartesIrmao")
                        .HasForeignKey("ParteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Irmao");

                    b.Navigation("Parte");
                });

            modelBuilder.Entity("Designa.Models.Parte", b =>
                {
                    b.HasOne("Designa.Models.Reuniao", "Reuniao")
                        .WithMany("Partes")
                        .HasForeignKey("ReuniaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reuniao");
                });

            modelBuilder.Entity("Designa.Models.Irmao", b =>
                {
                    b.Navigation("IrmaoPartes");
                });

            modelBuilder.Entity("Designa.Models.Parte", b =>
                {
                    b.Navigation("PartesIrmao");
                });

            modelBuilder.Entity("Designa.Models.Reuniao", b =>
                {
                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
