// <auto-generated />
using System;
using Designa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Designa.Migrations
{
    [DbContext(typeof(DesignaContext))]
    [Migration("20240407220712_AddColunasTbIrmaoEIrmaoParte")]
    partial class AddColunasTbIrmaoEIrmaoParte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("Designa.Models.Irmao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("EMenorIdade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaeId");

                    b.HasIndex("PaiId");

                    b.ToTable("Irmaos");
                });

            modelBuilder.Entity("Designa.Models.IrmaoParte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AjudanteId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AjudanteId");

                    b.HasIndex("ParteId");

                    b.HasIndex("PublicadorId");

                    b.ToTable("IrmaoPartes");
                });

            modelBuilder.Entity("Designa.Models.ListaNegra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IrmaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IrmaoListaNegraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IrmaoId");

                    b.HasIndex("IrmaoListaNegraId");

                    b.ToTable("ListasNegra");
                });

            modelBuilder.Entity("Designa.Models.Parte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Minutos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReuniaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReuniaoId");

                    b.ToTable("Partes");
                });

            modelBuilder.Entity("Designa.Models.Reuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Semana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reunioes");
                });

            modelBuilder.Entity("Designa.Models.Irmao", b =>
                {
                    b.HasOne("Designa.Models.Irmao", "Mae")
                        .WithMany()
                        .HasForeignKey("MaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Designa.Models.Irmao", "Pai")
                        .WithMany()
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mae");

                    b.Navigation("Pai");
                });

            modelBuilder.Entity("Designa.Models.IrmaoParte", b =>
                {
                    b.HasOne("Designa.Models.Irmao", "Ajudante")
                        .WithMany("PartesAjudante")
                        .HasForeignKey("AjudanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Designa.Models.Parte", "Parte")
                        .WithMany("PartesIrmao")
                        .HasForeignKey("ParteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Designa.Models.Irmao", "Publicador")
                        .WithMany("PartesPublicador")
                        .HasForeignKey("PublicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ajudante");

                    b.Navigation("Parte");

                    b.Navigation("Publicador");
                });

            modelBuilder.Entity("Designa.Models.ListaNegra", b =>
                {
                    b.HasOne("Designa.Models.Irmao", "Irmao")
                        .WithMany("listaNegraIrmaos")
                        .HasForeignKey("IrmaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Designa.Models.Irmao", "IrmaoListaNegra")
                        .WithMany()
                        .HasForeignKey("IrmaoListaNegraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Irmao");

                    b.Navigation("IrmaoListaNegra");
                });

            modelBuilder.Entity("Designa.Models.Parte", b =>
                {
                    b.HasOne("Designa.Models.Reuniao", "Reuniao")
                        .WithMany("Partes")
                        .HasForeignKey("ReuniaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reuniao");
                });

            modelBuilder.Entity("Designa.Models.Irmao", b =>
                {
                    b.Navigation("PartesAjudante");

                    b.Navigation("PartesPublicador");

                    b.Navigation("listaNegraIrmaos");
                });

            modelBuilder.Entity("Designa.Models.Parte", b =>
                {
                    b.Navigation("PartesIrmao");
                });

            modelBuilder.Entity("Designa.Models.Reuniao", b =>
                {
                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
